version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    networks:
      - default
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command: [
      "postgres",
      "-c", "log_statement=all",
      "-c", "fsync=off",
      "-c", "synchronous_commit=off",
      "-c", "full_page_writes=off"
    ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db:
    driver: local

networks:
  default:
