# Generated by Django 3.2.16 on 2023-04-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dramatiq_pg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backgroundjob',
            table='"dramatiq"."queue"',
        ),
    ]
