# Generated by Django 3.0.8 on 2020-07-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dramatiq_pg', '0002_auto_20200329_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundjob',
            options={},
        ),
    ]
