# Generated by Django 3.0.8 on 2020-07-29 02:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_dramatiq_pg', '0003_auto_20200729_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundjob',
            name='queue_name',
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='mtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='state',
            field=models.CharField(choices=[('queued', 'Queued'), ('consumed', 'Consumed'), ('rejected', 'Rejected'), ('done', 'Done')], default='queued', max_length=16),
        ),
        migrations.AddIndex(
            model_name='backgroundjob',
            index=models.Index(fields=['state', 'mtime'], name='queue_state_a7b80a_idx'),
        ),
    ]
